cmake_minimum_required(VERSION 3.15)
project(Game)
link_directories(${LIBPATH} ${SDL2_INCLUDE_DIRS})
include_directories(${CMAKE_SOURCE_DIR}/include ${SDL2_INCLUDE_DIRS})
aux_source_directory(./ SRC)
link_directories(${CMAKE_SOURCE_DIR}/lib ${SDL2_INCLUDE_DIRS})
link_libraries(Snake Fruit)
set(LIBRARY_OUTPUT_PATH ${LIBPATH})
add_library(Game STATIC ${SRC})
target_include_directories(Game ${SDL2_INCLUDE_DIRS})
target_link_libraries(Game ${SDL2_LIBRARIES})